site_name: ScriptSharks
site_description: Exploring the world of dangerous code.
site_author: Kristen M. Steffen
copyright: Copyright &copy; 2022 Kristen M. Steffen.<br>This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
site_url: https://www.scriptsharks.com/
repo_url: https://github.com/scriptsharks/scriptsharks.source
remote_branch: main
theme:
    name: null
    custom_dir: theme/mkdocs_windmill_dark
    history_buttons: false
    article_nav_top: true
    article_nav_bottom: true
extra:
    logo: img/logo.png
    version: 0.3.1
